#!/bin/bash

line="\n=======================================\n";
upg="sudo apt-get upgrade"
upd="sudo apt-get update"
ar="sudo apt-get autoremove"
ac="sudo apt-get autoclean"
clean="sudo apt-get clean"

echo -e "\nHi $(whoami)!\n"
echo -e "\nI need some information to install somethings for you."

echo -e "\nPlease, enter your github email account:\n"
read email

echo -e "\nPlease, enter your github username:\n"
read username

echo -e "\nTake a nap while I do the work for you ;)"

echo -e $line
echo "Upgrading apt-get..."
$upg

echo -e $line
echo "Updating apt-get..."
$upd

echo -e $line
echo "Removing garbage..."
$ar

echo -e $line
echo "Cleaning..."
$ac
$clean

echo -e $line
echo "Installing git..."
sudo apt-get install git

echo -e $line
echo "Installing SSH..."
sudo apt-get install ssh

echo -e $line
echo "Installing Gtkorphan..."
sudo apt-get install gtkorphan

echo -e $line
echo "Installing Gimp..."
sudo apt-get install gimp

echo -e $line
echo "Installing curl..."
sudo apt install curl

echo -e $line
echo "Installing sqlite, nodejs, yarn and stuff..."
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt-get update
sudo apt-get install git-core zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev software-properties-common libffi-dev nodejs yarn
sudo apt-get install gcc g++ make

echo -e $line
echo "Rbenv installation process..."
cd
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
exec $SHELL

git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
exec $SHELL

echo -e $line
echo "Installing ruby 2.7.0"
rbenv install 2.7.0
rbenv global 2.7.0
ruby -v

echo -e $line
echo "Installing bundler"
gem install bundler

echo -e $line
echo "Installing Rails 6.0.2.1"
gem install rails -v 6.0.2.1
rbenv rehash
rails -v

echo -e $line
echo "Installing Postgresql 10"
sudo apt install postgresql-10 libpq-dev
echo "Postgres user"
sudo -u postgres createuser $(whoami) -s

echo -e $line
echo -e "\nInstalling Snapd\n"
sudo apt install snapd

echo -e $line
echo -e "\nInstalling VLC\n"
sudo apt-get install vlc

echo -e $line
echo -e "\nInstalling Insomnia REST\n"
sudo snap install insomnia

echo -e $line
echo -e "\nDownloading Studio 3T\n"
wget -P ~/Downloads/ "https://download.studio3t.com/studio-3t/linux/2020.3.1/studio-3t-linux-x64.tar.gz"
tar -xvzf studio-3t-linux-x64.tar.gz
sh ./studio-3t-linux-x64.sh


echo -e $line
echo -e "\nConfiguring git\n"
git config --global color.ui true
git config --global user.name "$username"
git config --global user.email "$email"
ssh-keygen -t rsa -b 4096 -C "$email"

sudo apt-get install xclip
echo -e "Copying to clipboard you ssh key"
xclip -sel clip < ~/.ssh/id_rsa.pub
echo -e "\n1) Go to the following link https://github.com/settings/keys"
echo -e "\n2) Enter your github account credentials"
echo -e "\n3) Click on New SSH key button"
echo -e "\n4) Add a title and paste (ctrl+v) your SSH key on the key field"
echo -e "\n5) Click on Add SSH key"
